version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.http
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./backend/google-credentials.json:/app/google-credentials.json
      
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: